services:
  redis:
    image: redis:alpine
    container_name: librework-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:15
    container_name: librework-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: libreworkdb
      POSTGRES_USER: librework_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
