server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: LibreWork
  datasource:
    url: jdbc:postgresql://localhost:5432/libreworkdb
    username: librework_user
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
