server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: LibreWork
  datasource:
    url: jdbc:postgresql://localhost:5432/libreworkdb
    username: librework_user
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  jwt:
    secret: fc02e91fe82e6b624fc75502c5cd512d4514d996c43d0ee445a2ce07240f45d6
    expiration: 3600000
