name: CI with Maven

on:
  push:
    branches: [ "develop", "main"]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      posgres:
        image: posgres:15
        env:
          POSTGRES_DB: libreworkdb
          POSTGRES_USER: librework_user
          POSTGRES_PASSWORD: 123456
        port:
          - 5432:5432
        volumes:
          - postgres_data:/var/lib/postgresql/data

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B clean verify